import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header>
          <h1>Where is the world?</h1>
          <button>Dark Mode</button>
        </header>
        {children}
        <footer>
          <p>oneshi's FE Challenge 2024</p>
        </footer>
      </body>
    </html>
  );
}
